# Generated by Django 5.2 on 2025-04-12 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='DNI must contain between 8 and 20 digits.', regex='^\\d{8,20}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must have 9 to 11 digits, optionally starting with "+".', regex='^\\+?\\d{9,11}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_area',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Teaching area must contain only letters (max 30 characters).', regex='^[A-Za-zÀ-ÿ\\s]{1,30}$')]),
        ),
    ]
