# Generated by Django 5.2 on 2025-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_dni_alter_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='labor_condition',
            field=models.CharField(choices=[('nombrado', 'Nombrado'), ('contratado', 'Contratado'), ('jubilado', 'Jubilado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=10),
        ),
    ]
