# Generated by Django 5.2 on 2025-04-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_labor_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
