# Generated by Django 5.2 on 2025-04-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_bio_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
