# Generated by Django 5.2 on 2025-04-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('teacher', '0006_profilerole_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role'),
        ),
        migrations.DeleteModel(
            name='ProfileRole',
        ),
    ]
