# Generated by Django 5.2 on 2025-04-13 04:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Title must be 3–50 characters long and contain only letters, numbers, spaces, hyphens, underscores, or dots.', regex='^[A-Za-zÀ-ÿ0-9\\s\\-_.]{3,50}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('evaluation', 'Evaluation'), ('material', 'Material'), ('report', 'Report')], max_length=15)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('class_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_assignment.classassignment')),
            ],
        ),
    ]
