# Generated by Django 5.2 on 2025-04-12 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Course name must contain only letters and be up to 30 characters.', regex='^[A-Za-zÀ-ÿ\\s]{1,30}$')])),
                ('level', models.CharField(choices=[('initial', 'Initial'), ('primary', 'Primary'), ('secondary', 'Secondary')], max_length=10)),
            ],
        ),
    ]
