# Generated by Django 5.2 on 2025-04-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0002_alter_teacher_dni_alter_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('initial', 'Initial'), ('primary', 'Primary'), ('secondary', 'Secondary')], max_length=10)),
                ('grade', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=1)),
                ('academic_year', models.CharField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
