# Generated by Django 5.2 on 2025-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='level',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=10),
        ),
    ]
