# Generated by Django 5.2 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_assignment', '0002_alter_classassignment_level'),
        ('course', '0002_alter_course_level'),
        ('teacher', '0003_alter_teacher_labor_condition_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'course', 'level', 'grade', 'section', 'academic_year'), name='unique_class_assignment_per_year'),
        ),
    ]
