# Generated by Django 5.2 on 2025-04-13 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10, validators=[django.core.validators.RegexValidator(message='Day of the week must contain only letters.', regex='^[A-Za-zÀ-ÿ]+$')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_assignment.classassignment')),
            ],
        ),
    ]
