# Generated by Django 5.2 on 2025-04-18 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10, validators=[django.core.validators.RegexValidator(message='Day of the week must contain only letters.', regex='^[A-Za-zÀ-ÿ]+$')]),
        ),
    ]
