# Generated by Django 5.2 on 2025-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('docente', 'Docente'), ('alumno', 'Alumno'), ('director', 'Director'), ('subdirector', 'Subdirector'), ('coordinador', 'Coordinador'), ('secretaria', 'Secretaria'), ('administrador', 'Administrador'), ('apoderado', 'Apoderado')], max_length=20, unique=True, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
