# Generated by Django 5.2 on 2025-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('teacher', 'Docente'), ('student', 'Alumno'), ('director', 'Director'), ('subdirector', 'Subdirector'), ('coordinator', 'Coordinador'), ('secretary', 'Secretaria'), ('admin', 'Administrador'), ('authorized', 'Apoderado')], max_length=20, unique=True, verbose_name='Rol'),
        ),
    ]
